from enum import Enum

class ActionType(str, Enum):
    """The standard actions available to all creatures (2024 Rules)."""
    ATTACK = "Attack"
    DASH = "Dash"
    DISENGAGE = "Disengage"
    DODGE = "Dodge"
    HELP = "Help"
    HIDE = "Hide"
    INFLUENCE = "Influence"
    MAGIC = "Magic"
    READY = "Ready"
    SEARCH = "Search"
    STUDY = "Study"
    UTILIZE = "Utilize"

class Condition(str, Enum):
    """The standard conditions from the 2024 Rules Glossary."""
    BLINDED = "Blinded"
    CHARMED = "Charmed"
    DEAFENED = "Deafened"
    EXHAUSTION = "Exhaustion"
    FRIGHTENED = "Frightened"
    GRAPPLED = "Grappled"
    INCAPACITATED = "Incapacitated"
    INVISIBLE = "Invisible"
    PARALYZED = "Paralyzed"
    PETRIFIED = "Petrified"
    POISONED = "Poisoned"
    PRONE = "Prone"
    RESTRAINED = "Restrained"
    STUNNED = "Stunned"
    UNCONSCIOUS = "Unconscious"
    DEAD = "Dead"
